---
title: "Untitled"
format: html
---

# Handcoding Dataset Creation

```{r}
# libraries --------------------------------------------------------------

library(tidyverse)

# import data ------------------------------------------------------------

paragraphs_cleaned <- read_rds("Data/paragraphs_cleaned.rds")

# create dataset for labeling --------------------------------------------

# create a balanced dataset for labeling
# for the initial training of the classifier we want to have
# 1000 paragraphs labeled with an even distribution between french and german
# also: we want to have both climate related and not climate related paragraphs
# to achieve this, we will sample more paragraphs from businesses that have a
# higher chance of having climate related paragraphs
# final dataset should have:

# 50/50 distribution between french and german
# 70/30 distribution between Climate Businesses and not Climate Businesses

# groups_before <- transcripts_cleaned |>
#   count(ClimateBusiness, LanguageOfText) |>
#   mutate(percentage = n / sum(n) * 100)

set.seed(1234)
handcoding_dataset <- paragraphs_cleaned |>
  mutate(
    cb_weight = if_else(business_tag_climate == TRUE, 10, 1),
    lang_weight = if_else(LanguageOfText == "FR", 3, 1),
    weight = cb_weight * lang_weight
  ) |>
  slice_sample(
    n = 1000,
    weight_by = weight
  )

# groups_after <- transcripts_sampled |>
#   count(ClimateBusiness, LanguageOfText) |>
#   mutate(percentage = n / sum(n) * 100)

write_rds(handcoding_dataset, "Data/handcoding_dataset.rds")

# plot data ------------------------------------------------------------------

# transcripts_sampled <- readRDS("Data/transcripts_sampled.rds")
# transcripts_cleaned |> pull(paragraph) |> sample(10)

# plot distribution of text lengths
plot_word_count_distribution(
  data = handcoding_dataset,
  title = "Distribution of Paragraph Lengths in Handcoding Dataset",
  output_path = "Outputs/handcoding_dataset_text_length_distribution.png"
)

# plot distribution of languages
plot_categorical_distribution(
  data = handcoding_dataset,
  group_col = "LanguageOfText",
  title = "Distribution of Languages in Handcoding Dataset",
  x_label = "Language of Paragraphs",
  output_path = "Outputs/handcoding_dataset_language_distribution.png")

# plot business tag distribution
plot_categorical_distribution(
  data = handcoding_dataset,
  group_col = "business_tag_climate",
  x_label = "Energy, Transport or Environment Related Business",
  title = "Distribution of Business Tags in Handcoding Dataset",
  output_path = "Outputs/handcoding_dataset_business_tags_distribution.png"
)
```

# Translate paragraphs for handcoding

```{r}
# libraries --------------------------------------------------------------

library(tidyverse)
library(dotenv)
source("Scripts/00_functions.R")

# Translage  for handcoding ----------------------------------------------

handcoding_dataset <- read_rds("Data/handcoding_dataset.rds")

# # count characters in french
# transcripts_sampled |>
#   filter(LanguageOfText == "FR") |>
#   summarise(total_characters = sum(Textlength))

# Load Deepl Credentials
load_dot_env()

handcoding_dataset$paragraph_translated <- map_chr(
  handcoding_dataset$paragraph,
  deepl_translate,
  .progress = TRUE
)

handcoding_dataset_translated <- handcoding_dataset |>
  select(ID, ClimateBusiness, LanguageOfText, paragraph, paragraph_translated)

# handcoding_dataset <- readRDS("Data/handcoding_dataset.rds")
# transcripts_sampled <- readRDS("Data/transcripts_sampled.rds")
# handcoding_dataset <- inner_join(handcoding_dataset, transcripts_sampled, by = join_by(ID)) |> 
#   select(ID, ClimateBusiness.x, LanguageOfText.x, paragraph, paragraph_translated) |> 
#     rename(ClimateBusiness = ClimateBusiness.x, LanguageOfText = LanguageOfText.x)

# export to csv for labeling in label-studio
write_csv(handcoding_dataset_translated, "Data/handcoding_dataset_translated.csv")
```